"""empty message

Revision ID: 188f71601bef
Revises: 2451f997be2b
Create Date: 2025-06-05 00:41:28.915009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188f71601bef'
down_revision = '2451f997be2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_date', sa.String(length=120), nullable=False))
        batch_op.drop_column('invoice_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_data', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('invoice_date')

    # ### end Alembic commands ###
