"""empty message

Revision ID: 2451f997be2b
Revises: 0763d677d453
Create Date: 2025-06-05 00:29:05.073031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2451f997be2b'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_data', sa.String(length=120), nullable=False),
    sa.Column('invoice_number', sa.String(length=120), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    # ### end Alembic commands ###
